### ISSUE TITLE
Running on machine

### ISSUE THREAD

**Issue by BAATTS** [LegendaryBodyGuard/2DWinter#1]
#### Acceptance Criteria
- [x] Opening up scripts in Unity open rider
- [x] Clone repository 

#### Tasks
- [x] Link Rider to Unity 
- [x] Have the repository on your machine
