### ISSUE TITLE
Movement of player 

### ISSUE THREAD

**Issue by BAATTS** [LegendaryBodyGuard/2DWinter#3]
#### Acceptance Criteria
- [x] Be able to move using 'WASD' on Unity.

#### Tasks
- [x] Have an 2D object on screen that moves 
- [x] Create a script for movement
