### ISSUE TITLE
Background Images

### ISSUE THREAD

**Issue by BAATTS** [LegendaryBodyGuard/2DWinter#4]
#### Acceptance Criteria
- [ ] The background is visible when game is runnning

#### Tasks
- [ ] import a background asset
- [ ] Add the asset to the scene
